/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.locagyn.visao;

/**
 *
 * @author felip
 */
public class TelaHome extends javax.swing.JFrame {

    /**
     * Creates new form TelaHome
     */
    public TelaHome() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCategoria = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonMarcas = new javax.swing.JButton();
        jButtonModelos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonMarcas1 = new javax.swing.JButton();
        jButtonMarcas2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCategoria.setText("Cadastrar Categorias");
        jButtonCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 630, 210, 40));

        jButton1.setText("Cadastrar Acessorios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 210, 40));

        jButtonMarcas.setText("Cadrastrar Marcas");
        jButtonMarcas.setBorder(null);
        jButtonMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMarcasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 210, 40));

        jButtonModelos.setText("Cadrastrar Modelos");
        jButtonModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModelosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 210, 40));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/locagyn/gifseimagens/Post para instagram oportunidade venda de carros moderno vermelho (1).gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 730));

        jButtonMarcas1.setText("Cadrastrar Marcas");
        jButtonMarcas1.setBorder(null);
        jButtonMarcas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMarcas1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMarcas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 210, 40));

        jButtonMarcas2.setText("Cadrastrar Marcas");
        jButtonMarcas2.setBorder(null);
        jButtonMarcas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMarcas2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMarcas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 210, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMarcasActionPerformed
        // TODO add your handling code here:
       
        TelaDasMarcas frame = new TelaDasMarcas();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonMarcasActionPerformed

    private void jButtonModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModelosActionPerformed
        // TODO add your handling code here:
        TelaDosModelos frame = new TelaDosModelos();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonModelosActionPerformed

    private void jButtonMarcas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMarcas1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonMarcas1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         TelaAcessorios frame = new TelaAcessorios();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonMarcas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMarcas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMarcas2ActionPerformed

    private void jButtonCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriaActionPerformed
        // TODO add your handling code here:
        TelaCategorias frame = new TelaCategorias();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCategoria;
    private javax.swing.JButton jButtonMarcas;
    private javax.swing.JButton jButtonMarcas1;
    private javax.swing.JButton jButtonMarcas2;
    private javax.swing.JButton jButtonModelos;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

   
}
