/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.locagyn.visao;

import com.locagyn.Enumarations.SituacaoDoVeiculo;
import com.locagyn.Enumarations.TipoDeCombustivel;
import com.locagyn.Enumarations.TipoDoVeiculo;
import com.locagyn.LimitarCaracteres.LimitaCaracteres;
import com.locagyn.controle.CategoriaControle;
import com.locagyn.controle.IVeiculoControle;
import com.locagyn.controle.ModeloControle;
import com.locagyn.controle.VeiculoControle;
import com.locagyn.modelos.Categoria;
import com.locagyn.modelos.Modelo;
import com.locagyn.modelos.Veiculo;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ruben
 */
public class TelaVeiculo extends javax.swing.JFrame {
IVeiculoControle veiculoControl = new VeiculoControle();
ModeloControle objControl = new ModeloControle();
CategoriaControle catControl = new CategoriaControle();
    /**
     * Creates new form Tela2
     */
    public TelaVeiculo() {
        initComponents();
        setLocationRelativeTo(null);
        
        
        //criando metodo para a combobox
        loadComboBox();
          try {
            ArrayList<Modelo> dados = objControl.listagem();

            String[] linha = new String[dados.size()];
            for (int pos = 0; pos < dados.size(); pos++) {
                jComboBoxModelo.addItem(dados.get(pos).getDescricao());
            }
            ArrayList<Categoria> dadosCategoria = catControl.listagem();

            String[] listaCombo = new String[dadosCategoria.size()];
            for (int pos = 0; pos < dadosCategoria.size(); pos++) {
            listaCombo[pos] = dadosCategoria.get(pos).getDescricao();

                jComboBoxCategoria.addItem(listaCombo[pos]);
            }

            imprimirTabela(veiculoControl.listagem());

        } catch (Exception e) {
        }
        //jTextFieldAnoFabricacao.setDocument(new LimitaCaracteres(4, LimitaCaracteres.TipoEntrada.NUMEROINTEIRO));
        //jTextFieldAnoModelo.setDocument(new LimitaCaracteres(4, LimitaCaracteres.TipoEntrada.NUMEROINTEIRO));
        //jTextFieldPlaca.setDocument(new LimitaCaracteres(9, LimitaCaracteres.TipoEntrada.NOME));
        //jTextFieldPrecoCompra.setDocument(new LimitaCaracteres(12, LimitaCaracteres.TipoEntrada.NUMERODECIMAL));
       // jTextFieldPrecoVenda.setDocument(new LimitaCaracteres(12, LimitaCaracteres.TipoEntrada.NUMERODECIMAL));
       // jTextFieldQuilometragem.setDocument(new LimitaCaracteres(15, LimitaCaracteres.TipoEntrada.NUMERODECIMAL));
        //jTextFieldRenavam.setDocument(new LimitaCaracteres(12, LimitaCaracteres.TipoEntrada.NUMEROINTEIRO));
                         }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVeiculo = new javax.swing.JTable();
        jPanelRenavam = new javax.swing.JPanel();
        jTextFieldPlaca = new javax.swing.JTextField();
        jTextFieldRenavam = new javax.swing.JTextField();
        jTextFieldPrecoVenda = new javax.swing.JTextField();
        jLabelAnoFabricacao = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabelPrecoCompra = new javax.swing.JLabel();
        jLabelPrecoVenda = new javax.swing.JLabel();
        jTextFieldPrecoCompra = new javax.swing.JTextField();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelQuilometragem = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelCombustivel = new javax.swing.JLabel();
        jLabelTipoVeiculo = new javax.swing.JLabel();
        jTextFieldQuilometragem = new javax.swing.JTextField();
        jComboBoxCombustivel = new javax.swing.JComboBox<>();
        jLabelTipoVeiculo1 = new javax.swing.JLabel();
        jComboBoxSituacao = new javax.swing.JComboBox<>();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabelTipoVeiculo2 = new javax.swing.JLabel();
        jComboBoxModelo = new javax.swing.JComboBox<>();
        jLabelTipoVeiculo3 = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jFormattedTextFieldAnoModelo = new javax.swing.JTextField();
        jFormattedTextFieldAnoFabricacao1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonIncluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO VEICULO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        jTableVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PLACA", "RENAVAM", "PREÇO_COMPRA", "PREÇO_VENDA", "ANO_FABRICAÇÃO", "ANO_MODELO", "COMBUSTIVEL", "QUILOMETRAGEM", "TIPO", "SITUAÇÃO", "MODELO", "CATEGORIA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableVeiculo.setRowHeight(50);
        jTableVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVeiculoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableVeiculo);

        jTextFieldPlaca.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jTextFieldPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlacaActionPerformed(evt);
            }
        });

        jTextFieldRenavam.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextFieldRenavam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRenavamActionPerformed(evt);
            }
        });
        jTextFieldRenavam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRenavamKeyTyped(evt);
            }
        });

        jTextFieldPrecoVenda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldPrecoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecoVendaActionPerformed(evt);
            }
        });

        jLabelAnoFabricacao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelAnoFabricacao.setText("Ano de Fabricacao");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabelCpf.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelCpf.setText("Renavam");

        jLabelPrecoCompra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelPrecoCompra.setText("Preco de Compra");

        jLabelPrecoVenda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelPrecoVenda.setText("Preco de Venda");

        jTextFieldPrecoCompra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldPrecoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecoCompraActionPerformed(evt);
            }
        });

        jLabelPlaca.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelPlaca.setText("Placa");

        jLabelQuilometragem.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelQuilometragem.setText("Quilometragem");

        jLabelModelo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelModelo.setText("Ano do Modelo");

        jLabelCombustivel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelCombustivel.setText("Combustivel");

        jLabelTipoVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTipoVeiculo.setText("Tipo do Veiculo");

        jTextFieldQuilometragem.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jTextFieldQuilometragem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuilometragemActionPerformed(evt);
            }
        });

        jComboBoxCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCombustivelActionPerformed(evt);
            }
        });

        jLabelTipoVeiculo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTipoVeiculo1.setText("Situacao");

        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });

        jLabelTipoVeiculo2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTipoVeiculo2.setText("Categoria do Veiculo");

        jLabelTipoVeiculo3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTipoVeiculo3.setText("Modelo");

        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });

        jFormattedTextFieldAnoModelo.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jFormattedTextFieldAnoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldAnoModeloActionPerformed(evt);
            }
        });

        jFormattedTextFieldAnoFabricacao1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jFormattedTextFieldAnoFabricacao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldAnoFabricacao1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRenavamLayout = new javax.swing.GroupLayout(jPanelRenavam);
        jPanelRenavam.setLayout(jPanelRenavamLayout);
        jPanelRenavamLayout.setHorizontalGroup(
            jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRenavamLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelCpf)
                        .addComponent(jLabel5)
                        .addComponent(jLabelAnoFabricacao, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                        .addComponent(jLabelPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPrecoCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPrecoVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelTipoVeiculo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jTextFieldRenavam)
                    .addComponent(jTextFieldPrecoCompra)
                    .addComponent(jTextFieldPrecoVenda)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldAnoFabricacao1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRenavamLayout.createSequentialGroup()
                        .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCombustivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldAnoModelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelRenavamLayout.createSequentialGroup()
                        .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelQuilometragem)
                            .addComponent(jLabelTipoVeiculo)
                            .addComponent(jLabelTipoVeiculo1))
                        .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRenavamLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldQuilometragem, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jComboBoxSituacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanelRenavamLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jComboBoxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanelRenavamLayout.createSequentialGroup()
                        .addComponent(jLabelTipoVeiculo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelRenavamLayout.setVerticalGroup(
            jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRenavamLayout.createSequentialGroup()
                .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRenavamLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelCombustivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCombustivel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQuilometragem)
                            .addComponent(jTextFieldQuilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTipoVeiculo)
                            .addComponent(jComboBoxTipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRenavamLayout.createSequentialGroup()
                        .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelModelo)
                                .addComponent(jFormattedTextFieldAnoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRenavamLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelPlaca)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCpf)
                            .addComponent(jTextFieldRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrecoCompra)
                            .addComponent(jTextFieldPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrecoVenda)
                            .addComponent(jTextFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAnoFabricacao)
                            .addComponent(jLabelTipoVeiculo1)
                            .addComponent(jFormattedTextFieldAnoFabricacao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRenavamLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipoVeiculo2)
                            .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRenavamLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelRenavamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTipoVeiculo3))
                        .addContainerGap())))
        );

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/locagyn/icones/search.png"))); // NOI18N
        jButtonBuscar.setText("BUSCAR");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/locagyn/icones/add.png"))); // NOI18N
        jButtonIncluir.setText("INCLUIR");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/locagyn/icones/exchange1.png"))); // NOI18N
        jButtonAlterar.setText("ALTERAR");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonIncluir)
                    .addComponent(jButtonAlterar))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jButtonHome.setText("HOME");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jPanelRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(433, 433, 433)
                                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 90, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void imprimirTabela(ArrayList<Veiculo> listaDeVeiculos) {
        try {

            DefaultTableModel tabela = (DefaultTableModel) jTableVeiculo.getModel();
            tabela.setNumRows(0);
            Iterator<Veiculo> lista = listaDeVeiculos.iterator();
            while (lista.hasNext()) {
                String[] tab = new String[13];
                Veiculo aux = lista.next();
                tab[0] = aux.getId() + "";
                tab[1] = aux.getPlaca();
                tab[2] = aux.getRenavam();
                tab[3] = aux.getPrecoDeCompra() + "";
                tab[4] = aux.getPrecoDeVenda() + "";
                tab[5] = aux.getAnoFabricacao() + "";
                tab[6] = aux.getAnoModelo() + "";
                tab[7] = aux.getCombustivel().toString();
                tab[8] = aux.getQuilometragem() + "";
                tab[9] = aux.getTipoVeiculo().toString();
                tab[10] = aux.getSituacao().toString();
                tab[11] = objControl.buscar(aux.getModelo().getId()).getDescricao();
                tab[12] = catControl.buscar(aux.getCategoria().getId()).getDescricao();

                tabela.addRow(tab);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }
    private void jTableVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVeiculoMouseClicked
        // TODO add your handling code here:
        
        
        this.jTextFieldPlaca.setText((String) this.jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 1));
        this.jTextFieldRenavam.setText((String) this.jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 2));
        this.jTextFieldPrecoCompra.setText((String) this.jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 3));
        this.jTextFieldPrecoVenda.setText((String) this.jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 4));
        this.jFormattedTextFieldAnoFabricacao1.setText((String) this.jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 5));
        this.jFormattedTextFieldAnoModelo.setText((String) this.jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 6));
        this.jComboBoxCombustivel.setSelectedItem((String) this.jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 7));
        this.jTextFieldQuilometragem.setText((String) this.jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 8));
        this.jComboBoxTipo.setSelectedItem((String) this.jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 9));
        this.jComboBoxSituacao.setSelectedItem((String) this.jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 10));
        this.jComboBoxModelo.setSelectedItem((String) this.jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 11));
        this.jComboBoxCategoria.setSelectedItem((String) this.jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 12));
     
    }//GEN-LAST:event_jTableVeiculoMouseClicked

    private void jTextFieldPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlacaActionPerformed

    private void jTextFieldRenavamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRenavamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRenavamActionPerformed

    private void jTextFieldRenavamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRenavamKeyTyped
        // TODO add your handling code here:

      
        
    }//GEN-LAST:event_jTextFieldRenavamKeyTyped

    private void jTextFieldPrecoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecoVendaActionPerformed

    private void jTextFieldPrecoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecoCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecoCompraActionPerformed

    private void jTextFieldQuilometragemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuilometragemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuilometragemActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        // TODO add your handling code here:
        try {
            int idModelo = 0;
            int idcat = 0;

            Veiculo obj = new Veiculo(0, jTextFieldPlaca.getText(), jTextFieldRenavam.getText(), Float.parseFloat(jTextFieldPrecoCompra.getText()), Float.parseFloat(jTextFieldPrecoVenda.getText()), Integer.parseInt(jFormattedTextFieldAnoModelo.getText()), Integer.parseInt(jFormattedTextFieldAnoModelo.getText()), TipoDeCombustivel.valueOf(jComboBoxCombustivel.getSelectedItem().toString()), Integer.parseInt(jTextFieldQuilometragem.getText()), TipoDoVeiculo.valueOf(jComboBoxTipo.getSelectedItem().toString()), SituacaoDoVeiculo.valueOf(jComboBoxSituacao.getSelectedItem().toString()), objControl.buscar(idModelo), catControl.buscar(idcat));
            ArrayList<Modelo> lista = objControl.listagem();
            for (int i = 0; i < lista.size(); i++) {
                if (jComboBoxModelo.getSelectedItem().equals(lista.get(i).getDescricao())) {
                    obj.setModelo(lista.get(i));
                }
            }
            ArrayList<Categoria> dadosCat = catControl.listagem();
            for (int pos = 0; pos < dadosCat.size(); pos++) {
                if (jComboBoxCategoria.getSelectedItem().equals(dadosCat.get(pos).getDescricao())) {
                    obj.setCategoria(dadosCat.get(pos));
                }
            }
            veiculoControl.incluir(obj);
            imprimirTabela(veiculoControl.listagem());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
      
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
         try {
            int idModelo = 0;
            int idcat = 0;

            Veiculo obj = new Veiculo(0, jTextFieldPlaca.getText(), jTextFieldRenavam.getText(), Float.parseFloat(jTextFieldPrecoCompra.getText()), Float.parseFloat(jTextFieldPrecoVenda.getText()), Integer.parseInt(jFormattedTextFieldAnoModelo.getText()), Integer.parseInt(jFormattedTextFieldAnoModelo.getText()), TipoDeCombustivel.valueOf(jComboBoxCombustivel.getSelectedItem().toString()), Integer.parseInt(jTextFieldQuilometragem.getText()), TipoDoVeiculo.valueOf(jComboBoxTipo.getSelectedItem().toString()), SituacaoDoVeiculo.valueOf(jComboBoxSituacao.getSelectedItem().toString()), objControl.buscar(idModelo), catControl.buscar(idcat));
            ArrayList<Modelo> lista = objControl.listagem();
            for (int i = 0; i < lista.size(); i++) {
                if (jComboBoxModelo.getSelectedItem().equals(lista.get(i).getDescricao())) {
                    obj.setModelo(lista.get(i));
                }
            }
            ArrayList<Categoria> dadosCat = catControl.listagem();
            for (int pos = 0; pos < dadosCat.size(); pos++) {
                if (jComboBoxCategoria.getSelectedItem().equals(dadosCat.get(pos).getDescricao())) {
                    obj.setCategoria(dadosCat.get(pos));
                }
            }
            veiculoControl.alterar(obj);
            imprimirTabela(veiculoControl.listagem());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        TelaHome frame = new TelaHome();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jComboBoxCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCombustivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCombustivelActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jFormattedTextFieldAnoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldAnoModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldAnoModeloActionPerformed

    private void jFormattedTextFieldAnoFabricacao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldAnoFabricacao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldAnoFabricacao1ActionPerformed

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<TipoDeCombustivel> jComboBoxCombustivel;
    private javax.swing.JComboBox<String> jComboBoxModelo;
    private javax.swing.JComboBox<SituacaoDoVeiculo> jComboBoxSituacao;
    private javax.swing.JComboBox<TipoDoVeiculo> jComboBoxTipo;
    private javax.swing.JTextField jFormattedTextFieldAnoFabricacao1;
    private javax.swing.JTextField jFormattedTextFieldAnoModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAnoFabricacao;
    private javax.swing.JLabel jLabelCombustivel;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelPrecoCompra;
    private javax.swing.JLabel jLabelPrecoVenda;
    private javax.swing.JLabel jLabelQuilometragem;
    private javax.swing.JLabel jLabelTipoVeiculo;
    private javax.swing.JLabel jLabelTipoVeiculo1;
    private javax.swing.JLabel jLabelTipoVeiculo2;
    private javax.swing.JLabel jLabelTipoVeiculo3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelRenavam;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableVeiculo;
    private javax.swing.JTextField jTextFieldPlaca;
    private javax.swing.JTextField jTextFieldPrecoCompra;
    private javax.swing.JTextField jTextFieldPrecoVenda;
    private javax.swing.JTextField jTextFieldQuilometragem;
    private javax.swing.JTextField jTextFieldRenavam;
    // End of variables declaration//GEN-END:variables

    //metodo criado para integrar a combobox com a enumaration de combustiveis
    private void loadComboBox() {
        jComboBoxCombustivel.setModel(new DefaultComboBoxModel<>(TipoDeCombustivel.values()));
        jComboBoxSituacao.setModel(new DefaultComboBoxModel<>(SituacaoDoVeiculo.values()));
        jComboBoxTipo.setModel(new DefaultComboBoxModel<>(TipoDoVeiculo.values()));
    }
}
